#!/bin/bash


SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
MCB_PATH=/opt/mcb32tools # default location - needs update otherwise

RPATH=${SCRIPT_DIR}/runtime #${BASH_SOURCE[0]}/runtime
BPATH=${PWD}/bin #${BASH_SOURCE[0]}/runtime

if [ -f ${MCB_PATH}/environment ]; then
	source ${MCB_PATH}/environment
fi
yellow=$(tput setaf 3)
white=$(tput sgr0)
[[ $PS1 =~ 'kta' ]] || export PS1="\[$yellow\][kta]\[$white\] $PS1"
unset yellow
unset white

export KTA_WCET_RUNTIME_PATH=$RPATH
export PATH="${BPATH}:${PATH}"

# ulimit -Sv 500000
